---
# tasks file for ansible-role-mac

- name: Install homebrew
  import_tasks: homebrew.yml
  tags:
    - homebrew
    - install
    - formula
    - cask
    - xattrs
    - shells
  when:
    - ansible_distribution == 'MacOSX'


# Tasks to remove my homebrew bits
- name: Homebrew Killer
  import_tasks: homebrew-killer.yml
  tags:
    - homebrew
    - killer
  when:
    - ansible_distribution == 'MacOSX'
    - kill_my_mac == true
